// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNXuOVGlbfnpT7rMeprkvDjWPN0pxRZ_g',
    appId: '1:947506832753:web:3de212811f79e5fd3e42d0',
    messagingSenderId: '947506832753',
    projectId: 'iot-ejemplo-a1232',
    authDomain: 'iot-ejemplo-a1232.firebaseapp.com',
    databaseURL: 'https://iot-ejemplo-a1232-default-rtdb.firebaseio.com',
    storageBucket: 'iot-ejemplo-a1232.firebasestorage.app',
    measurementId: 'G-1P559MTH96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9kGigbKa1ncZJWgEeuWz413nRNu-tMFI',
    appId: '1:947506832753:android:86ba4e0bc261613b3e42d0',
    messagingSenderId: '947506832753',
    projectId: 'iot-ejemplo-a1232',
    databaseURL: 'https://iot-ejemplo-a1232-default-rtdb.firebaseio.com',
    storageBucket: 'iot-ejemplo-a1232.firebasestorage.app',
  );
}
